name: Build Native Module

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    strategy:
      matrix:
        architecture: [x64]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    
    - name: Build native module
      run: npm run build-native
      env:
        npm_config_target_arch: ${{ matrix.architecture }}
    
    - name: Copy built module to release folder
      run: |
        if not exist build\Release mkdir build\Release
        copy "src\native\network\build\Release\network.node" "build\Release\network.node"
      shell: cmd
    
    - name: Upload network.node artifact
      uses: actions/upload-artifact@v4
      with:
        name: network-node-${{ matrix.architecture }}
        path: build/Release/network.node
        retention-days: 30
    
    - name: Verify native module was built
      run: |
        if exist "build\Release\network.node" (
          echo ✓ Native module built successfully
          dir "build\Release\network.node"
        ) else (
          echo ✗ Native module not found
          exit 1
        )
      shell: cmd